### PR TITLE
react1-week2

### PR DESCRIPTION
**Pull request by AnB801**

### CODE REVIEW

**Review by LucasIversen — CHANGES_REQUESTED** [review]
This is a class component, which we don't really like using since it is not supported by react anymore. Instead we use the function component like we do in class:

```javascript
export function App(props) {
}
```

You can use all the same lifetime tools in the function component as in the class component, so for states, we use the `useState` hook, for componentDidMount, we use the `useEffect` with an empty array as paramather(meaning that it only fires on mount), and for the componentWillUnmount, we make a return statement in our aforementioned useEffect hook, meaning something like this:

```javascript
useEffect(() => {
   //Code that runs when useEffect runs
   return () => {
      //Code that runs when the component unmount 
   }
}, [//when should this code run again]);
```

So, here's what I'd like you to do to "reactify" this exercise a bit more:

- rewrite the app component as a class component with react hooks (useState, useEffect)
- put the code inside your `{todos.map((todo) => (` inside a separate todo component (remember that we can give a child component a function as a prop)

**Comment by AnB801** [comment]
Hi , I rewrote the code according to your comments, can you cheсk

**Comment by LucasIversen** [comment]
Hi again Anton. Yeah, it looks good. Good job 👌

**Comment by AnB801** [comment]
Thank you for such a quick check

**Pull request merged**
